/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carcomparison;

import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Collection;

import javax.swing.DefaultListModel;

/**
 *
 * @author Stephen Yamonaco
 */
public class CarComparison extends javax.swing.JFrame {

    /**
     * Creates new form CarComparison
     */
    public CarComparison() {
        initComponents();
        // Jpanel size
//		this.setBounds(720, 120, 2378, 1800);
//		this.setResizable(false);
//
//		// koenigsegg stats on panel
//		ArrayList<Car> carList1 = CarList.listOfCars();
//		Car koenigsegg = carList1.get(1);
//		Collection<String> data1 = koenigsegg.getAttributes().keySet();
//		DefaultListModel list1 = new DefaultListModel();
//		for (int i = 0; i < data1.size(); i++) {
//			list1.addElement(data1.toArray()[i] + ": " + koenigsegg.getAtrribute((String) data1.toArray()[i]));
//		}
//		jList1.setModel(list1);
//
//		// koenigsegg list size
//		jPanel3.setPreferredSize(new Dimension(1120, 800));
//		jList1.setFont(new Font("Times New Roman", Font.ROMAN_BASELINE, 112));
//
//		// pagani stats on panel
//		ArrayList<Car> carList2 = CarList.listOfCars();
//		Car pagani = carList2.get(2);
//		Collection<String> data2 = pagani.getAttributes().keySet();
//		DefaultListModel list2 = new DefaultListModel();
//		for (int i = 0; i < data2.size(); i++) {
//			list2.addElement(data2.toArray()[i] + ": " + pagani.getAtrribute((String) data2.toArray()[i]));
//		}
//		jList2.setModel(list2);
//
//		// pagani list size
//		jPanel2.setPreferredSize(new Dimension(1120, 800));
//		jList2.setFont(new Font("Times New Roman", Font.ROMAN_BASELINE, 112));
//
//		// Lamborghini stats on panel
//		ArrayList<Car> carList3 = CarList.listOfCars();
//		Car lamborghini = carList3.get(0);
//		Collection<String> data3 = lamborghini.getAttributes().keySet();
//		DefaultListModel list3 = new DefaultListModel();
//		for (int i = 0; i < data3.size(); i++) {
//			list3.addElement(data3.toArray()[i] + ": " + lamborghini.getAtrribute((String) data3.toArray()[i]));
//		}
//		jList3.setModel(list3);
//
//		// Lamboghini list size
//		jPanel4.setPreferredSize(new Dimension(1120, 800));
//		jList3.setFont(new Font("Times New Roman", Font.ROMAN_BASELINE, 112));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carPanel1 = new carcomparison.CarPanel();
        carPanel2 = new carcomparison.CarPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(carPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarComparison().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private carcomparison.CarPanel carPanel1;
    private carcomparison.CarPanel carPanel2;
    // End of variables declaration//GEN-END:variables
}
